# Generated by Django 3.1.2 on 2020-11-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20201106_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='isTranding',
            field=models.BooleanField(default=False),
        ),
    ]
