# Generated by Django 3.1.2 on 2020-11-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20201106_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='coverPic',
            field=models.ImageField(default='/default_cover.png', upload_to='cover_photos/'),
        ),
    ]
