# Generated by Django 3.1.2 on 2020-11-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20201106_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='catagory',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='coverPic',
            field=models.ImageField(default='/cover_photos/default_cover.png', upload_to='cover_photos/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='website.Tag'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='catagories',
            field=models.ManyToManyField(blank=True, to='website.Catagory'),
        ),
    ]
