# Generated by Django 3.1.2 on 2020-11-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201106_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='catagory',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='catagory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.catagory'),
        ),
    ]
