# Generated by Django 3.1.2 on 2020-11-07 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_catagory_tranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
