# Generated by Django 3.1.2 on 2020-11-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0016_catagory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fb_url', models.CharField(blank=True, max_length=250, null=True)),
                ('yt_url', models.CharField(blank=True, max_length=250, null=True)),
                ('pint_url', models.CharField(blank=True, max_length=250, null=True)),
                ('twit_url', models.CharField(blank=True, max_length=250, null=True)),
                ('flickr_url', models.CharField(blank=True, max_length=250, null=True)),
                ('insta_url', models.CharField(blank=True, max_length=250, null=True)),
                ('gp_url', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
