# Generated by Django 3.1.2 on 2020-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='gp_url',
            new_name='personal_url',
        ),
        migrations.AddField(
            model_name='author',
            name='coverPic',
            field=models.ImageField(default='/author_profile_pic/default.png', upload_to='author_profile_pic/'),
        ),
    ]
