# Generated by Django 3.1.2 on 2020-11-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20201106_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='catagory',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='catagory',
            field=models.ManyToManyField(blank=True, to='website.Catagory'),
        ),
    ]
