# Generated by Django 3.1.2 on 2020-11-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20201107_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='coverPic',
            new_name='profile_pic',
        ),
    ]
