# Generated by Django 3.1.2 on 2020-11-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20201108_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fb_url',
            new_name='facebook_URL',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='flickr_url',
            new_name='flicker_URL',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='insta_url',
            new_name='instagram_URL',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='personal_url',
            new_name='personal_URL',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='pint_url',
            new_name='pinterest_URL',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='twit_url',
            new_name='twitter_URL',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='yt_url',
            new_name='youtube_URL',
        ),
    ]
